-- SQLite
SELECT avg(sepal_length) FROM iris_table,target_table
GROUP BY TARGET;



CREATE TABLE IRIS(
SEPAL_LENGTH REAL NULL,
SEPAL_WIDTH REAL NULL,
PETAL_LENGTH REAL NULL,
PETAL_WIDTH REAL NULL,
TARGET REAL NULL,
COUNT REAL NULL
);

INSERT INTO IRIS 
SELECT AVG(SEPAL_LENGTH),AVG(SEPAL_WIDTH),AVG(PETAL_LENGTH),AVG(PETAL_WIDTH),TARGET,COUNT(*)
FROM iris_table,target_table
GROUP BY TARGET;

DROP TABLE IRIS;